import { type User, type InsertUser, type AITool, type SearchQuery, type ToolsResponse, type FeaturedToolsResponse, categories, pricingTypes } from "@shared/schema";
import { randomUUID } from "crypto";

export interface IStorage {
  getUser(id: string): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  
  getAllTools(): Promise<AITool[]>;
  getToolBySlug(slug: string): Promise<AITool | undefined>;
  getToolById(id: string): Promise<AITool | undefined>;
  searchTools(query: SearchQuery): Promise<ToolsResponse>;
  getFeaturedTools(): Promise<FeaturedToolsResponse>;
  getRelatedTools(category: string, excludeId?: string): Promise<AITool[]>;
}

const generateMockTools = (): AITool[] => {
  const tools: AITool[] = [
    {
      id: "1",
      name: "ChatGPT",
      slug: "chatgpt",
      tagline: "مساعد ذكاء اصطناعي متقدم للحوار والكتابة وحل المشاكل",
      description: "ChatGPT هو مساعد ذكاء اصطناعي قوي طورته OpenAI يمكن أن يساعدك في مجموعة واسعة من المهام بما في ذلك الكتابة والتحليل والبرمجة والرياضيات والمشاريع الإبداعية. يستخدم نماذج لغة متقدمة لفهم السياق وتقديم ردود مفيدة وحقيقية. سواء كنت تحتاج إلى مساعدة في صياغة بريد إلكتروني أو حل مشكلة معقدة، فإن ChatGPT مصمم لمساعدتك بفعالية وكفاءة.",
      category: "Personal",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://chat.openai.com",
      iconColor: "#10A37F",
      iconInitials: "GP",
      votes: 125847,
      saves: 45230,
      views: 2500000,
      rating: 4.8,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-11-30T00:00:00Z",
      features: ["Natural language understanding", "Code generation", "Creative writing", "Math problem solving", "Multi-language support", "Context retention"],
      tags: ["chatbot", "AI assistant", "writing", "productivity", "coding"]
    },
    {
      id: "2",
      name: "Midjourney",
      slug: "midjourney",
      tagline: "توليد صور بقوة الذكاء الاصطناعي من وصف نصي",
      description: "Midjourney هو مولد فن ذكاء اصطناعي مبتكر ينشئ صورًا مذهلة من الموجهات النصية. يستخدم التعلم الآلي المتقدم لتحويل أفكارك إلى روائع بصرية. يستخدم الفنانون والمصممون والمبدعون Midjourney لاستكشاف مفاهيم بصرية جديدة وإنشاء فن المفاهيم وتوليد الصور الفريدة للمشاريع المختلفة.",
      category: "Images",
      pricing: "Paid",
      priceDetails: "from $10/mo",
      websiteUrl: "https://midjourney.com",
      iconColor: "#000000",
      iconInitials: "MJ",
      votes: 98234,
      saves: 32100,
      views: 1800000,
      rating: 4.9,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-07-12T00:00:00Z",
      features: ["Text-to-image generation", "Style customization", "High-resolution output", "Variation generation", "Upscaling", "Community gallery"],
      tags: ["image generation", "art", "design", "creative", "AI art"]
    },
    {
      id: "3",
      name: "Claude",
      slug: "claude",
      tagline: "مساعد ذكاء اصطناعي مفيد وآمن وصادق من Anthropic",
      description: "Claude هو مساعد ذكاء اصطناعي أنشأته Anthropic ليكون مفيدًا وآمنًا وصادقًا. يتفوق في الحوار المدروس وإنشاء المحتوى والبرمجة والمهام التحليلية. تم تصميم Claude مع الأمان في الاعتبار ويمكنه التعامل مع المحادثات المعقدة والدقيقة مع الحفاظ على الردود المفيدة والأخلاقية.",
      category: "Work",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://claude.ai",
      iconColor: "#D97757",
      iconInitials: "CL",
      votes: 87654,
      saves: 28900,
      views: 1500000,
      rating: 4.7,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2023-03-14T00:00:00Z",
      features: ["Long context window", "Code analysis", "Document summarization", "Creative writing", "Research assistance", "Multi-turn conversations"],
      tags: ["AI assistant", "chatbot", "writing", "research", "coding"]
    },
    {
      id: "4",
      name: "DALL-E 3",
      slug: "dalle-3",
      tagline: "إنشاء صور وفن واقعية من وصف اللغة الطبيعية",
      description: "DALL-E 3 هو أحدث نموذج توليد صور من OpenAI ينشئ صورًا مفصلة وحقيقية للغاية من الموجهات النصية. يفهم الدقائق والتفاصيل في الموجهات، مما يسهل ترجمة أفكارك إلى الصورة المطلوبة بالضبط. مع التكامل مع ChatGPT، يوفر تجربة إبداعية سلسة.",
      category: "Images",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://openai.com/dall-e-3",
      iconColor: "#412991",
      iconInitials: "D3",
      votes: 76543,
      saves: 24500,
      views: 1200000,
      rating: 4.6,
      isFeatured: true,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-10-01T00:00:00Z",
      features: ["High fidelity images", "Text rendering", "ChatGPT integration", "Safety features", "Prompt understanding", "Style variety"],
      tags: ["image generation", "art", "creative", "AI art", "text-to-image"]
    },
    {
      id: "5",
      name: "GitHub Copilot",
      slug: "github-copilot",
      tagline: "مبرمج مساعد بالذكاء الاصطناعي يساعدك على كتابة الكود بسرعة",
      description: "GitHub Copilot هو أداة إكمال كود مدعومة بالذكاء الاصطناعي تساعد المطورين على كتابة الكود بسرعة وبجهد أقل. يقترح أسطرًا أو كتل برمجية كاملة أثناء الكتابة، ويتعلم من سياق مشروعك. مع التدريب على مليارات الأسطر البرمجية، يساعدك Copilot على اكتشاف طرق جديدة لحل المشاكل وكتابة كود أفضل.",
      category: "Code",
      pricing: "Paid",
      priceDetails: "$10/mo",
      websiteUrl: "https://github.com/features/copilot",
      iconColor: "#24292E",
      iconInitials: "GC",
      votes: 72341,
      saves: 21890,
      views: 980000,
      rating: 4.5,
      isFeatured: true,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-06-21T00:00:00Z",
      features: ["Code completion", "Multi-language support", "IDE integration", "Context awareness", "Documentation generation", "Test generation"],
      tags: ["coding", "developer tools", "productivity", "code completion", "AI programming"]
    },
    {
      id: "6",
      name: "Notion AI",
      slug: "notion-ai",
      tagline: "مساعد الكتابة والإنتاجية المدعوم بالذكاء الاصطناعي في Notion",
      description: "Notion AI يعزز مساحة عمل Notion الخاصة بك بإمكانيات الذكاء الاصطناعي. يمكنه مساعدتك في الكتابة والعصف الذهني والتلخيص وترجمة المحتوى مباشرة في ملاحظاتك ومستنداتك. مع التكامل السلس في تجربة Notion، فإنه يساعدك على العمل بذكاء أكبر وأسرع.",
      category: "Productivity",
      pricing: "Paid",
      priceDetails: "$10/mo",
      websiteUrl: "https://notion.so/product/ai",
      iconColor: "#000000",
      iconInitials: "NA",
      votes: 65432,
      saves: 19870,
      views: 850000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-02-22T00:00:00Z",
      features: ["Writing assistance", "Summarization", "Translation", "Brainstorming", "Action items extraction", "Meeting notes"],
      tags: ["productivity", "writing", "notes", "workspace", "collaboration"]
    },
    {
      id: "7",
      name: "Jasper",
      slug: "jasper",
      tagline: "منصة محتوى بالذكاء الاصطناعي لفرق التسويق",
      description: "Jasper هي منصة محتوى بالذكاء الاصطناعي مصممة لفرق التسويق. تساعد في إنشاء نسخة تسويقية عالية الجودة ومقالات مدونة ومحتوى وسائل التواصل الاجتماعي والمزيد. بفضل تدريب صوت العلامة التجارية ميزات التعاون الجماعي، تضمن Jasper محتوى متسق وموافق للعلامة التجارية على نطاق واسع.",
      category: "Marketing",
      pricing: "Paid",
      priceDetails: "from $39/mo",
      websiteUrl: "https://jasper.ai",
      iconColor: "#FF5733",
      iconInitials: "JP",
      votes: 54321,
      saves: 16540,
      views: 720000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-01-15T00:00:00Z",
      features: ["Marketing copy", "Blog writing", "Brand voice", "Team collaboration", "Templates", "SEO optimization"],
      tags: ["marketing", "copywriting", "content", "SEO", "branding"]
    },
    {
      id: "8",
      name: "Runway",
      slug: "runway",
      tagline: "أدوات تحرير وتوليد فيديو مدعومة بالذكاء الاصطناعي",
      description: "Runway هي مجموعة إبداعية من الجيل التالي مع أدوات تحرير فيديو مدعومة بالذكاء الاصطناعي. من توليد النص إلى الفيديو إلى ميزات تحرير الفيديو المتقدمة، يمكّن Runway المبدعين من تحقيق رؤاهم بدون القيود التقليدية.",
      category: "Videos",
      pricing: "Freemium",
      priceDetails: "from $12/mo",
      websiteUrl: "https://runway.ml",
      iconColor: "#8B5CF6",
      iconInitials: "RW",
      votes: 48765,
      saves: 15230,
      views: 650000,
      rating: 4.5,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-09-01T00:00:00Z",
      features: ["Text-to-video", "Video editing", "Green screen removal", "Motion tracking", "Inpainting", "Image generation"],
      tags: ["video", "editing", "creative", "motion", "AI video"]
    },
    {
      id: "9",
      name: "Grammarly",
      slug: "grammarly",
      tagline: "مساعد الكتابة المدعوم بالذكاء الاصطناعي للتواصل الأفضل",
      description: "Grammarly هي مساعد كتابة شامل يستخدم الذكاء الاصطناعي لمساعدتك على الكتابة بوضوح وثقة وخالية من الأخطاء. من النحو والتهجئة إلى اقتراحات النبرة والأسلوب، تساعدك Grammarly على التواصل بفعالية عبر المنصات.",
      category: "Writing",
      pricing: "Freemium",
      priceDetails: "from $12/mo",
      websiteUrl: "https://grammarly.com",
      iconColor: "#15C39A",
      iconInitials: "GR",
      votes: 89123,
      saves: 28760,
      views: 1100000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2009-08-01T00:00:00Z",
      features: ["Grammar checking", "Spelling correction", "Tone detection", "Plagiarism detection", "Style suggestions", "Browser extension"],
      tags: ["writing", "grammar", "productivity", "communication", "editing"]
    },
    {
      id: "10",
      name: "Eleven Labs",
      slug: "eleven-labs",
      tagline: "منصة توليف الصوت والنص إلى كلام بالذكاء الاصطناعي",
      description: "تقدم Eleven Labs تكنولوجيا توليف الصوت بالذكاء الاصطناعي المتقدمة. أنشئ تعليقات صوتية حقيقية واستنسخ الأصوات وأنشئ كلامًا بلغات متعددة بطريقة طبيعية وتنوع عاطفي لم يسبق له مثيل.",
      category: "Audio",
      pricing: "Freemium",
      priceDetails: "from $5/mo",
      websiteUrl: "https://elevenlabs.io",
      iconColor: "#000000",
      iconInitials: "11",
      votes: 67890,
      saves: 22340,
      views: 890000,
      rating: 4.7,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-01-01T00:00:00Z",
      features: ["Voice cloning", "Text-to-speech", "Multiple languages", "Emotion control", "API access", "Audio editing"],
      tags: ["voice", "audio", "text-to-speech", "voice cloning", "narration"]
    },
    {
      id: "11",
      name: "Perplexity AI",
      slug: "perplexity-ai",
      tagline: "محرك بحث مدعوم بالذكاء الاصطناعي مع مصادر مستشهد بها",
      description: "Perplexity AI هو محرك إجابات يستخدم الذكاء الاصطناعي لتقديم إجابات مباشرة على أسئلتك مع مصادر مستشهد بها. يجمع قوة نماذج اللغة الكبيرة مع البحث عن الويب في الوقت الفعلي لتزويدك بمعلومات دقيقة وحديثة.",
      category: "Research",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://perplexity.ai",
      iconColor: "#1FB8CD",
      iconInitials: "PX",
      votes: 56789,
      saves: 18920,
      views: 780000,
      rating: 4.6,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-12-01T00:00:00Z",
      features: ["Cited answers", "Real-time search", "Follow-up questions", "Source verification", "Copilot mode", "Collections"],
      tags: ["search", "research", "AI search", "citations", "knowledge"]
    },
    {
      id: "12",
      name: "Copy.ai",
      slug: "copy-ai",
      tagline: "أداة كتابة إعلانية بالذكاء الاصطناعي للمحتوى التسويقي",
      description: "Copy.ai تساعدك على إنشاء نسخ تسويقية ومقالات مدونة ووصف منتجات والمزيد باستخدام الذكاء الاصطناعي. تقدم قوالب وسير عمل متنوعة لتبسيط عملية إنشاء المحتوى وزيادة الإنتاجية.",
      category: "Marketing",
      pricing: "Freemium",
      priceDetails: "from $49/mo",
      websiteUrl: "https://copy.ai",
      iconColor: "#7C3AED",
      iconInitials: "CA",
      votes: 43210,
      saves: 14560,
      views: 560000,
      rating: 4.2,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2020-10-01T00:00:00Z",
      features: ["Marketing copy", "Blog posts", "Product descriptions", "Email writing", "Social media", "Workflows"],
      tags: ["copywriting", "marketing", "content", "writing", "automation"]
    },
    {
      id: "13",
      name: "Synthesia",
      slug: "synthesia",
      tagline: "إنشاء فيديوهات ذكاء اصطناعي مع أفاتارات افتراضية",
      description: "Synthesia تتيح لك إنشاء فيديوهات احترافية مع أفاتارات ذكاء اصطناعي. اكتب نصك واختر أفاتار وأنشئ فيديوهات بجودة الاستوديو في دقائق. مثالية للتدريب والتسويق والاتصالات الداخلية.",
      category: "Videos",
      pricing: "Paid",
      priceDetails: "from $22/mo",
      websiteUrl: "https://synthesia.io",
      iconColor: "#00B4D8",
      iconInitials: "SY",
      votes: 38765,
      saves: 12890,
      views: 480000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-04-01T00:00:00Z",
      features: ["AI avatars", "Text-to-video", "Multiple languages", "Custom avatars", "Templates", "Brand customization"],
      tags: ["video", "avatars", "training", "marketing", "AI video"]
    },
    {
      id: "14",
      name: "Descript",
      slug: "descript",
      tagline: "تحرير الصوت والفيديو المدعوم بالذكاء الاصطناعي بطريقة بسيطة",
      description: "Descript هو محرر صوت وفيديو تعاوني يعمل مثل المستند. حرر الوسائط بتعديل النص وأزل الكلمات الحشو تلقائيًا واستخدم ميزات الذكاء الاصطناعي لتحسين سير عمل إنشاء المحتوى.",
      category: "Audio",
      pricing: "Freemium",
      priceDetails: "from $12/mo",
      websiteUrl: "https://descript.com",
      iconColor: "#2DD4BF",
      iconInitials: "DS",
      votes: 35678,
      saves: 11230,
      views: 420000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2019-01-01T00:00:00Z",
      features: ["Text-based editing", "Transcription", "Filler word removal", "Screen recording", "Overdub", "Collaboration"],
      tags: ["audio", "video", "editing", "podcast", "transcription"]
    },
    {
      id: "15",
      name: "Writesonic",
      slug: "writesonic",
      tagline: "منصة كتابة ذكاء اصطناعي للمحتوى وتحسين محركات البحث",
      description: "Writesonic هي منصة كتابة بالذكاء الاصطناعي تساعدك على إنشاء محتوى محسن لمحركات البحث ومقالات مدونة وإعلانات والمزيد. مع ميزات مثل Chatsonic وكاتب المقالات تبسط عملية إنشاء المحتوى للمسوقين والشركات.",
      category: "Writing",
      pricing: "Freemium",
      priceDetails: "from $16/mo",
      websiteUrl: "https://writesonic.com",
      iconColor: "#6366F1",
      iconInitials: "WS",
      votes: 32456,
      saves: 10890,
      views: 390000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-01-01T00:00:00Z",
      features: ["Blog writing", "SEO optimization", "Chatsonic", "Article Writer", "AI images", "Landing pages"],
      tags: ["writing", "SEO", "content", "blog", "marketing"]
    },
    {
      id: "16",
      name: "Leonardo AI",
      slug: "leonardo-ai",
      tagline: "إنشاء موارد لعبة وفن مذهلة مع الذكاء الاصطناعي",
      description: "Leonardo AI هي منصة ذكاء اصطناعي توليدية تركز على إنشاء موارد بصرية بجودة الإنتاج. شهيرة بشكل خاص بين مطوري الألعاب والفنانين والمحترفين الإبداعيين لتوليد فن عالي الجودة وثابت.",
      category: "Images",
      pricing: "Freemium",
      priceDetails: "from $12/mo",
      websiteUrl: "https://leonardo.ai",
      iconColor: "#8B5CF6",
      iconInitials: "LA",
      votes: 45678,
      saves: 15670,
      views: 580000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: true,
      releasedAt: "2023-01-01T00:00:00Z",
      features: ["Image generation", "Game assets", "Consistent style", "Training models", "Alchemy", "Real-time canvas"],
      tags: ["image generation", "game art", "design", "creative", "AI art"]
    },
    {
      id: "17",
      name: "Otter.ai",
      slug: "otter-ai",
      tagline: "مساعد اجتماعات ذكاء اصطناعي للنسخ والملاحظات",
      description: "Otter.ai هو مساعد اجتماعات مدعوم بالذكاء الاصطناعي يوفر نسخ فوري وملاحظات اجتماعات آلية وملخصات. يتكامل مع أدوات المؤتمرات الفيديوية الشهيرة لالتقاط وتنظيم رؤى الاجتماعات.",
      category: "Productivity",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://otter.ai",
      iconColor: "#3B82F6",
      iconInitials: "OT",
      votes: 41234,
      saves: 13450,
      views: 510000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2017-02-01T00:00:00Z",
      features: ["Real-time transcription", "Meeting summaries", "Action items", "Zoom integration", "Search transcripts", "Collaboration"],
      tags: ["transcription", "meetings", "productivity", "notes", "collaboration"]
    },
    {
      id: "18",
      name: "Canva AI",
      slug: "canva-ai",
      tagline: "أدوات تصميم مدعومة بالذكاء الاصطناعي داخل Canva",
      description: "Canva AI يجلب الذكاء الاصطناعي إلى منصة التصميم الشهيرة. تتضمن الميزات Magic Write و Text to Image و Magic Eraser والمزيد مما يجعل التصميم الاحترافي في متناول الجميع.",
      category: "Design",
      pricing: "Freemium",
      priceDetails: "from $13/mo",
      websiteUrl: "https://canva.com",
      iconColor: "#00C4CC",
      iconInitials: "CV",
      votes: 78901,
      saves: 26780,
      views: 920000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-03-01T00:00:00Z",
      features: ["Magic Write", "Text to Image", "Magic Eraser", "Background remover", "Templates", "Brand kit"],
      tags: ["design", "graphics", "templates", "creative", "marketing"]
    },
    {
      id: "19",
      name: "Pictory",
      slug: "pictory",
      tagline: "تحويل المحتوى الطويل إلى فيديوهات قصيرة مع الذكاء الاصطناعي",
      description: "Pictory تستخدم الذكاء الاصطناعي لتحويل محتواك الطويل إلى فيديوهات جذابة قصيرة. تستخرج تلقائيًا النقاط الرئيسية وتضيف عناوين وتنشئ مقاطع جاهزة لوسائل التواصل من المدونات والندوات والبودكاست.",
      category: "Videos",
      pricing: "Paid",
      priceDetails: "from $19/mo",
      websiteUrl: "https://pictory.ai",
      iconColor: "#E11D48",
      iconInitials: "PI",
      votes: 28765,
      saves: 9870,
      views: 350000,
      rating: 4.2,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-06-01T00:00:00Z",
      features: ["Blog to video", "Auto-captions", "Text-based editing", "Stock media", "Branding", "Social optimization"],
      tags: ["video", "content repurposing", "social media", "marketing", "automation"]
    },
    {
      id: "20",
      name: "Murf AI",
      slug: "murf-ai",
      tagline: "مولد صوت ذكاء اصطناعي لتعليقات صوتية",
      description: "Murf AI هو مولد صوت ذكاء اصطناعي متعدد الاستخدامات ينشئ تعليقات صوتية بجودة الاستوديو. مع 120+ صوت في 20+ لغة فهي مثالية للفيديوهات والعروض التقديمية والبودكاست والمزيد.",
      category: "Audio",
      pricing: "Freemium",
      priceDetails: "from $19/mo",
      websiteUrl: "https://murf.ai",
      iconColor: "#F97316",
      iconInitials: "MF",
      votes: 34567,
      saves: 11230,
      views: 410000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2020-08-01T00:00:00Z",
      features: ["Voice generation", "120+ voices", "20+ languages", "Voice cloning", "Video sync", "API access"],
      tags: ["voice", "voiceover", "audio", "narration", "text-to-speech"]
    },
    {
      id: "21",
      name: "Fireflies.ai",
      slug: "fireflies-ai",
      tagline: "مساعد اجتماعات ذكاء اصطناعي ينسخ ويحلل المحادثات",
      description: "Fireflies.ai هو مساعد اجتماعات بالذكاء الاصطناعي يسجل وينسخ ويحلل محادثاتك الصوتية تلقائيًا. يعمل مع منصات المؤتمرات الفيديوية الشهيرة ويوفر نصوص قابلة للبحث مع ملخصات تم إنشاؤها بالذكاء الاصطناعي.",
      category: "Productivity",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://fireflies.ai",
      iconColor: "#6366F1",
      iconInitials: "FF",
      votes: 29876,
      saves: 9650,
      views: 340000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2018-01-01T00:00:00Z",
      features: ["Auto-transcription", "Meeting summaries", "Action items", "CRM integration", "Analytics", "Search"],
      tags: ["meetings", "transcription", "productivity", "collaboration", "notes"]
    },
    {
      id: "22",
      name: "Replit AI",
      slug: "replit-ai",
      tagline: "AI-powered coding assistant in your browser",
      description: "Replit AI is an AI coding assistant built into the Replit IDE. It helps you write, debug, and understand code with AI-powered suggestions, explanations, and code generation capabilities.",
      category: "Code",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://replit.com",
      iconColor: "#F26207",
      iconInitials: "RP",
      votes: 42345,
      saves: 14230,
      views: 520000,
      rating: 4.5,
      isFeatured: true,
      isNew: false,
      isTrending: true,
      releasedAt: "2023-04-01T00:00:00Z",
      features: ["Code completion", "Chat assistant", "Code explanation", "Debugging help", "Multi-language", "Collaborative coding"],
      tags: ["coding", "IDE", "developer tools", "AI programming", "learning"]
    },
    {
      id: "23",
      name: "Gamma",
      slug: "gamma",
      tagline: "Create beautiful presentations with AI",
      description: "Gamma is a new medium for presenting ideas, powered by AI. It helps you create beautiful, engaging presentations, documents, and webpages in minutes, not hours.",
      category: "Productivity",
      pricing: "Freemium",
      priceDetails: "from $8/mo",
      websiteUrl: "https://gamma.app",
      iconColor: "#7C3AED",
      iconInitials: "GM",
      votes: 38901,
      saves: 12780,
      views: 460000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-08-01T00:00:00Z",
      features: ["AI-generated slides", "Beautiful templates", "Interactive content", "One-click styling", "Analytics", "Embedding"],
      tags: ["presentations", "slides", "documents", "productivity", "design"]
    },
    {
      id: "24",
      name: "Tome",
      slug: "tome",
      tagline: "AI-powered storytelling and presentation tool",
      description: "Tome is a generative storytelling format that lets you create compelling narratives with AI. It generates text, images, and layouts to help you share ideas more effectively.",
      category: "Creativity",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://tome.app",
      iconColor: "#000000",
      iconInitials: "TM",
      votes: 31234,
      saves: 10450,
      views: 380000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-09-01T00:00:00Z",
      features: ["AI generation", "Storytelling", "Image creation", "Templates", "Collaboration", "Sharing"],
      tags: ["presentations", "storytelling", "creative", "AI content", "design"]
    },
    {
      id: "25",
      name: "Stable Diffusion",
      slug: "stable-diffusion",
      tagline: "Open-source AI image generation model",
      description: "Stable Diffusion is a powerful open-source text-to-image AI model. It can generate detailed images from text descriptions and is widely used for artistic creation, design work, and research purposes.",
      category: "Images",
      pricing: "Free",
      websiteUrl: "https://stability.ai",
      iconColor: "#9333EA",
      iconInitials: "SD",
      votes: 67890,
      saves: 23450,
      views: 890000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-08-22T00:00:00Z",
      features: ["Text-to-image", "Open source", "Local running", "Fine-tuning", "Inpainting", "Variations"],
      tags: ["image generation", "open source", "AI art", "creative", "design"]
    },
    {
      id: "26",
      name: "Adobe Firefly",
      slug: "adobe-firefly",
      tagline: "Adobe's creative generative AI for content creation",
      description: "Adobe Firefly is a family of creative generative AI models designed to be commercially safe. It powers AI features across Adobe products for image generation, text effects, and creative editing.",
      category: "Images",
      pricing: "Freemium",
      priceDetails: "from $5/mo",
      websiteUrl: "https://firefly.adobe.com",
      iconColor: "#FF6B00",
      iconInitials: "AF",
      votes: 52341,
      saves: 17890,
      views: 680000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-03-21T00:00:00Z",
      features: ["Text-to-image", "Generative fill", "Text effects", "Vector recoloring", "Sketch to image", "Commercial safe"],
      tags: ["image generation", "design", "creative", "Adobe", "commercial"]
    },
    {
      id: "27",
      name: "Zapier AI",
      slug: "zapier-ai",
      tagline: "AI automation assistant for connecting apps",
      description: "Zapier AI helps you build automated workflows using natural language. Describe what you want to automate, and AI will help you create the perfect Zap to connect your apps and streamline your work.",
      category: "Productivity",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://zapier.com",
      iconColor: "#FF4A00",
      iconInitials: "ZP",
      votes: 47890,
      saves: 15670,
      views: 590000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-05-01T00:00:00Z",
      features: ["Natural language automation", "5000+ apps", "Chatbots", "Tables", "Interfaces", "AI actions"],
      tags: ["automation", "integration", "productivity", "workflow", "no-code"]
    },
    {
      id: "28",
      name: "Anthropic Claude API",
      slug: "claude-api",
      tagline: "Enterprise-grade AI assistant API",
      description: "The Claude API provides developers access to Anthropic's AI assistant for building applications. It offers various model sizes optimized for different use cases, from fast responses to complex reasoning.",
      category: "Code",
      pricing: "Paid",
      priceDetails: "usage-based",
      websiteUrl: "https://anthropic.com/api",
      iconColor: "#D97757",
      iconInitials: "CA",
      votes: 34567,
      saves: 11230,
      views: 420000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-07-11T00:00:00Z",
      features: ["Multiple models", "Long context", "Function calling", "Vision", "Enterprise security", "Custom training"],
      tags: ["API", "developer tools", "AI assistant", "enterprise", "coding"]
    },
    {
      id: "29",
      name: "Suno AI",
      slug: "suno-ai",
      tagline: "Create music with AI from text prompts",
      description: "Suno AI generates original music from text descriptions. Create songs with vocals, instruments, and various genres just by describing what you want to hear. Perfect for creators who need custom audio.",
      category: "Audio",
      pricing: "Freemium",
      priceDetails: "from $8/mo",
      websiteUrl: "https://suno.ai",
      iconColor: "#F472B6",
      iconInitials: "SN",
      votes: 45678,
      saves: 16780,
      views: 620000,
      rating: 4.7,
      isFeatured: true,
      isNew: true,
      isTrending: true,
      releasedAt: "2024-01-15T00:00:00Z",
      features: ["Text-to-music", "Vocals generation", "Multiple genres", "Lyrics writing", "Instrumental tracks", "Remixing"],
      tags: ["music", "audio", "creative", "AI music", "composition"]
    },
    {
      id: "30",
      name: "Pika Labs",
      slug: "pika-labs",
      tagline: "AI video generation and editing platform",
      description: "Pika Labs offers AI-powered video generation that creates and edits videos from text prompts and images. Generate creative video content with natural motion and cinematic quality.",
      category: "Videos",
      pricing: "Freemium",
      priceDetails: "from $8/mo",
      websiteUrl: "https://pika.art",
      iconColor: "#EC4899",
      iconInitials: "PK",
      votes: 41234,
      saves: 14560,
      views: 540000,
      rating: 4.5,
      isFeatured: true,
      isNew: true,
      isTrending: true,
      releasedAt: "2024-01-01T00:00:00Z",
      features: ["Text-to-video", "Image-to-video", "Video editing", "Motion control", "Style transfer", "Lip sync"],
      tags: ["video", "AI video", "creative", "motion", "editing"]
    },
    {
      id: "31",
      name: "Luma AI",
      slug: "luma-ai",
      tagline: "Capture and create 3D content with AI",
      description: "Luma AI uses neural radiance fields to capture photorealistic 3D content from photos and videos. Create stunning 3D scenes and objects for games, VR, and visual effects.",
      category: "Images",
      pricing: "Freemium",
      websiteUrl: "https://lumalabs.ai",
      iconColor: "#3B82F6",
      iconInitials: "LM",
      votes: 29876,
      saves: 10890,
      views: 380000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-11-01T00:00:00Z",
      features: ["3D capture", "NeRF technology", "Photorealistic", "Mobile app", "API access", "Export formats"],
      tags: ["3D", "capture", "creative", "VR", "photogrammetry"]
    },
    {
      id: "32",
      name: "Cursor",
      slug: "cursor",
      tagline: "AI-first code editor for faster development",
      description: "Cursor is an AI-first code editor built to make you extraordinarily productive. It understands your codebase, suggests edits, and helps you write code faster with AI assistance.",
      category: "Code",
      pricing: "Freemium",
      priceDetails: "from $20/mo",
      websiteUrl: "https://cursor.sh",
      iconColor: "#000000",
      iconInitials: "CR",
      votes: 38901,
      saves: 13450,
      views: 490000,
      rating: 4.7,
      isFeatured: true,
      isNew: true,
      isTrending: true,
      releasedAt: "2023-10-01T00:00:00Z",
      features: ["AI code editing", "Codebase understanding", "Chat interface", "Multi-file edits", "VS Code compatible", "Terminal integration"],
      tags: ["coding", "IDE", "developer tools", "AI programming", "productivity"]
    },
    {
      id: "33",
      name: "Tabnine",
      slug: "tabnine",
      tagline: "AI code assistant for teams",
      description: "Tabnine is an AI code assistant that helps development teams write code faster. It provides intelligent code completions trained on your codebase while ensuring privacy and security.",
      category: "Code",
      pricing: "Freemium",
      priceDetails: "from $12/mo",
      websiteUrl: "https://tabnine.com",
      iconColor: "#6366F1",
      iconInitials: "TN",
      votes: 28765,
      saves: 9870,
      views: 340000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2019-01-01T00:00:00Z",
      features: ["Code completion", "Private hosting", "Team training", "IDE plugins", "Code patterns", "Security focus"],
      tags: ["coding", "code completion", "developer tools", "privacy", "enterprise"]
    },
    {
      id: "34",
      name: "Codeium",
      slug: "codeium",
      tagline: "Free AI coding assistant",
      description: "Codeium offers a free AI-powered code completion and chat assistant. It supports 70+ languages and integrates with popular IDEs to help developers write code faster.",
      category: "Code",
      pricing: "Free",
      websiteUrl: "https://codeium.com",
      iconColor: "#06B6D4",
      iconInitials: "CD",
      votes: 35678,
      saves: 12340,
      views: 450000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: true,
      releasedAt: "2022-11-01T00:00:00Z",
      features: ["Code completion", "Chat assistant", "70+ languages", "Free for individuals", "IDE integration", "Fast inference"],
      tags: ["coding", "free", "code completion", "developer tools", "IDE"]
    },
    {
      id: "35",
      name: "Hugging Face",
      slug: "hugging-face",
      tagline: "The AI community building the future",
      description: "Hugging Face is the leading platform for machine learning models, datasets, and AI applications. It hosts thousands of open-source models and provides tools for training, deploying, and sharing AI.",
      category: "Data",
      pricing: "Freemium",
      priceDetails: "from $9/mo",
      websiteUrl: "https://huggingface.co",
      iconColor: "#FFD21E",
      iconInitials: "HF",
      votes: 67890,
      saves: 24560,
      views: 920000,
      rating: 4.8,
      isFeatured: true,
      isNew: false,
      isTrending: false,
      releasedAt: "2016-01-01T00:00:00Z",
      features: ["Model hub", "Datasets", "Spaces", "Transformers library", "Inference API", "AutoTrain"],
      tags: ["ML platform", "open source", "models", "research", "community"]
    },
    {
      id: "36",
      name: "Replicate",
      slug: "replicate",
      tagline: "Run ML models in the cloud",
      description: "Replicate makes it easy to run machine learning models in the cloud. Access thousands of models through a simple API and scale your AI applications without managing infrastructure.",
      category: "Code",
      pricing: "Paid",
      priceDetails: "usage-based",
      websiteUrl: "https://replicate.com",
      iconColor: "#000000",
      iconInitials: "RE",
      votes: 31234,
      saves: 11230,
      views: 390000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2020-01-01T00:00:00Z",
      features: ["Model hosting", "API access", "Custom models", "Serverless", "Version control", "Fine-tuning"],
      tags: ["ML platform", "API", "cloud", "developer tools", "infrastructure"]
    },
    {
      id: "37",
      name: "Krisp",
      slug: "krisp",
      tagline: "AI-powered noise cancellation for calls",
      description: "Krisp uses AI to remove background noise, echo, and voices from your calls. It works with any communication app to ensure crystal-clear audio quality for remote meetings and calls.",
      category: "Audio",
      pricing: "Freemium",
      priceDetails: "from $8/mo",
      websiteUrl: "https://krisp.ai",
      iconColor: "#6366F1",
      iconInitials: "KR",
      votes: 27654,
      saves: 9230,
      views: 320000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2018-01-01T00:00:00Z",
      features: ["Noise cancellation", "Echo removal", "Voice isolation", "Meeting transcription", "Talk time analytics", "Works with any app"],
      tags: ["audio", "noise cancellation", "meetings", "productivity", "communication"]
    },
    {
      id: "38",
      name: "Mem",
      slug: "mem",
      tagline: "AI-powered note-taking and knowledge management",
      description: "Mem is a self-organizing workspace that uses AI to help you capture, organize, and retrieve information. It automatically connects related notes and surfaces relevant information when you need it.",
      category: "Productivity",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://mem.ai",
      iconColor: "#000000",
      iconInitials: "MM",
      votes: 24567,
      saves: 8760,
      views: 290000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2020-06-01T00:00:00Z",
      features: ["Self-organizing", "AI connections", "Smart search", "Meeting notes", "Templates", "Collaboration"],
      tags: ["notes", "knowledge management", "productivity", "AI organization", "workspace"]
    },
    {
      id: "39",
      name: "Lavender",
      slug: "lavender",
      tagline: "AI email assistant for sales",
      description: "Lavender is an AI email coach that helps sales professionals write better emails. It scores your emails, provides suggestions, and helps you personalize outreach for better response rates.",
      category: "Sales",
      pricing: "Freemium",
      priceDetails: "from $29/mo",
      websiteUrl: "https://lavender.ai",
      iconColor: "#8B5CF6",
      iconInitials: "LV",
      votes: 21345,
      saves: 7890,
      views: 260000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-01-01T00:00:00Z",
      features: ["Email scoring", "Personalization", "Tone analysis", "Best practices", "CRM integration", "Team analytics"],
      tags: ["sales", "email", "outreach", "productivity", "communication"]
    },
    {
      id: "40",
      name: "Gong",
      slug: "gong",
      tagline: "AI revenue intelligence platform",
      description: "Gong captures and analyzes customer interactions using AI. It provides insights from sales calls, emails, and meetings to help teams understand what works and close more deals.",
      category: "Sales",
      pricing: "Paid",
      priceDetails: "custom pricing",
      websiteUrl: "https://gong.io",
      iconColor: "#7C3AED",
      iconInitials: "GO",
      votes: 34567,
      saves: 11890,
      views: 420000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2015-01-01T00:00:00Z",
      features: ["Call recording", "Conversation analytics", "Deal intelligence", "Coaching", "Forecasting", "Integrations"],
      tags: ["sales", "analytics", "conversation intelligence", "revenue", "enterprise"]
    },
    {
      id: "41",
      name: "Intercom Fin",
      slug: "intercom-fin",
      tagline: "AI customer service agent",
      description: "Fin is Intercom's AI agent that provides instant, accurate answers to customer questions. It learns from your help content and conversations to resolve issues without human intervention.",
      category: "Customer Support",
      pricing: "Paid",
      priceDetails: "from $0.99/resolution",
      websiteUrl: "https://intercom.com/fin",
      iconColor: "#6366F1",
      iconInitials: "FN",
      votes: 29876,
      saves: 10450,
      views: 370000,
      rating: 4.5,
      isFeatured: true,
      isNew: true,
      isTrending: false,
      releasedAt: "2024-02-01T00:00:00Z",
      features: ["AI resolution", "Knowledge learning", "Multi-language", "Handoff to humans", "Analytics", "Custom training"],
      tags: ["customer support", "chatbot", "AI agent", "automation", "service"]
    },
    {
      id: "42",
      name: "Zendesk AI",
      slug: "zendesk-ai",
      tagline: "AI-powered customer service solutions",
      description: "Zendesk AI enhances customer service with intelligent automation. It includes AI agents, intelligent triage, suggestions for agents, and automated responses to improve support efficiency.",
      category: "Customer Support",
      pricing: "Paid",
      priceDetails: "custom pricing",
      websiteUrl: "https://zendesk.com/ai",
      iconColor: "#03363D",
      iconInitials: "ZD",
      votes: 38901,
      saves: 13450,
      views: 480000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-05-01T00:00:00Z",
      features: ["AI agents", "Intelligent triage", "Agent suggestions", "Automation", "Knowledge base", "Analytics"],
      tags: ["customer support", "helpdesk", "automation", "enterprise", "service"]
    },
    {
      id: "43",
      name: "Khan Academy Khanmigo",
      slug: "khanmigo",
      tagline: "AI tutor and teaching assistant",
      description: "Khanmigo is Khan Academy's AI tutor that provides personalized learning support. It helps students learn through guided Socratic dialogue and assists teachers with lesson planning and insights.",
      category: "Education",
      pricing: "Paid",
      priceDetails: "$4/mo",
      websiteUrl: "https://khanmigo.ai",
      iconColor: "#14BF96",
      iconInitials: "KM",
      votes: 27654,
      saves: 9870,
      views: 340000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-03-14T00:00:00Z",
      features: ["Personalized tutoring", "Socratic method", "Teacher tools", "Writing support", "Math help", "Safe for students"],
      tags: ["education", "tutoring", "learning", "students", "teachers"]
    },
    {
      id: "44",
      name: "Duolingo Max",
      slug: "duolingo-max",
      tagline: "AI-powered language learning features",
      description: "Duolingo Max adds AI-powered features to the popular language learning app. Roleplay conversations with AI characters and get detailed explanations of your mistakes to learn faster.",
      category: "Education",
      pricing: "Paid",
      priceDetails: "$30/mo",
      websiteUrl: "https://duolingo.com/max",
      iconColor: "#58CC02",
      iconInitials: "DL",
      votes: 34567,
      saves: 12340,
      views: 450000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-03-14T00:00:00Z",
      features: ["Roleplay", "Explain my answer", "Conversation practice", "Personalized feedback", "Multiple languages", "Gamification"],
      tags: ["education", "languages", "learning", "practice", "mobile"]
    },
    {
      id: "45",
      name: "Elicit",
      slug: "elicit",
      tagline: "AI research assistant for literature review",
      description: "Elicit uses AI to help researchers find, analyze, and synthesize academic papers. It extracts key information from papers, identifies relevant studies, and helps with literature reviews.",
      category: "Research",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://elicit.org",
      iconColor: "#6366F1",
      iconInitials: "EL",
      votes: 31234,
      saves: 11890,
      views: 390000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2021-01-01T00:00:00Z",
      features: ["Paper search", "Information extraction", "Summarization", "Citation management", "Concept mapping", "Export"],
      tags: ["research", "academic", "papers", "literature review", "science"]
    },
    {
      id: "46",
      name: "Consensus",
      slug: "consensus",
      tagline: "AI-powered academic search engine",
      description: "Consensus uses AI to search and synthesize research papers. Ask questions in plain language and get evidence-based answers with citations from peer-reviewed scientific literature.",
      category: "Research",
      pricing: "Freemium",
      priceDetails: "from $7/mo",
      websiteUrl: "https://consensus.app",
      iconColor: "#059669",
      iconInitials: "CN",
      votes: 28765,
      saves: 10230,
      views: 350000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-01-01T00:00:00Z",
      features: ["Question answering", "Paper synthesis", "Citations", "Yes/No meter", "Filters", "Academic focus"],
      tags: ["research", "academic", "search", "evidence-based", "science"]
    },
    {
      id: "47",
      name: "Harvey",
      slug: "harvey",
      tagline: "AI for legal professionals",
      description: "Harvey is an AI assistant built specifically for legal work. It helps lawyers with research, document analysis, contract review, and drafting while maintaining confidentiality and accuracy.",
      category: "Legal",
      pricing: "Paid",
      priceDetails: "custom pricing",
      websiteUrl: "https://harvey.ai",
      iconColor: "#1E3A5F",
      iconInitials: "HV",
      votes: 24567,
      saves: 8760,
      views: 290000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-11-01T00:00:00Z",
      features: ["Legal research", "Contract analysis", "Document drafting", "Due diligence", "Case law search", "Confidential"],
      tags: ["legal", "law", "contracts", "research", "enterprise"]
    },
    {
      id: "48",
      name: "Casetext",
      slug: "casetext",
      tagline: "AI legal research and document review",
      description: "Casetext offers CoCounsel, an AI legal assistant for legal research, document review, and deposition preparation. It helps legal professionals work more efficiently with AI-powered tools.",
      category: "Legal",
      pricing: "Paid",
      priceDetails: "custom pricing",
      websiteUrl: "https://casetext.com",
      iconColor: "#2563EB",
      iconInitials: "CT",
      votes: 21345,
      saves: 7650,
      views: 260000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2013-01-01T00:00:00Z",
      features: ["CoCounsel AI", "Legal research", "Document review", "Deposition prep", "Contract analysis", "Parallel search"],
      tags: ["legal", "research", "documents", "law firms", "enterprise"]
    },
    {
      id: "49",
      name: "Viz.ai",
      slug: "viz-ai",
      tagline: "AI for coordinated care in healthcare",
      description: "Viz.ai uses AI to analyze medical imaging and alert care teams to potential issues. It helps hospitals identify conditions like stroke and pulmonary embolism faster for better patient outcomes.",
      category: "Healthcare",
      pricing: "Paid",
      priceDetails: "custom pricing",
      websiteUrl: "https://viz.ai",
      iconColor: "#DC2626",
      iconInitials: "VZ",
      votes: 19876,
      saves: 6890,
      views: 240000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2018-01-01T00:00:00Z",
      features: ["Medical imaging AI", "Care coordination", "Stroke detection", "Real-time alerts", "FDA cleared", "EHR integration"],
      tags: ["healthcare", "medical imaging", "diagnosis", "hospitals", "AI detection"]
    },
    {
      id: "50",
      name: "Glass Health",
      slug: "glass-health",
      tagline: "AI clinical decision support for doctors",
      description: "Glass Health provides AI-powered clinical decision support for healthcare providers. It generates differential diagnoses and clinical plans based on patient information.",
      category: "Healthcare",
      pricing: "Freemium",
      websiteUrl: "https://glass.health",
      iconColor: "#0891B2",
      iconInitials: "GH",
      votes: 17654,
      saves: 6230,
      views: 210000,
      rating: 4.4,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2022-01-01T00:00:00Z",
      features: ["Differential diagnosis", "Clinical plans", "Medical knowledge base", "Evidence-based", "Provider focused", "Quick access"],
      tags: ["healthcare", "clinical", "diagnosis", "doctors", "medical"]
    },
    {
      id: "51",
      name: "Ramp Intelligence",
      slug: "ramp-intelligence",
      tagline: "AI-powered corporate card and finance automation",
      description: "Ramp uses AI to help businesses control spending, automate expense management, and find savings. Its AI features automatically categorize expenses, detect anomalies, and negotiate vendor savings.",
      category: "Finance",
      pricing: "Free",
      websiteUrl: "https://ramp.com",
      iconColor: "#22C55E",
      iconInitials: "RM",
      votes: 34567,
      saves: 12340,
      views: 420000,
      rating: 4.6,
      isFeatured: false,
      isNew: false,
      isTrending: true,
      releasedAt: "2019-01-01T00:00:00Z",
      features: ["Expense categorization", "Savings finder", "Anomaly detection", "Receipt matching", "Vendor negotiations", "Reporting"],
      tags: ["finance", "expense management", "corporate card", "automation", "savings"]
    },
    {
      id: "52",
      name: "Socratic by Google",
      slug: "socratic",
      tagline: "AI homework helper for students",
      description: "Socratic by Google helps students understand homework problems. Take a photo of a question and get step-by-step explanations, videos, and learning resources powered by Google AI.",
      category: "Education",
      pricing: "Free",
      websiteUrl: "https://socratic.org",
      iconColor: "#4285F4",
      iconInitials: "SC",
      votes: 45678,
      saves: 16890,
      views: 580000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2017-01-01T00:00:00Z",
      features: ["Photo-based help", "Step-by-step solutions", "Multiple subjects", "Video explanations", "Learning resources", "Free to use"],
      tags: ["education", "homework", "students", "learning", "free"]
    },
    {
      id: "53",
      name: "Buffer AI Assistant",
      slug: "buffer-ai",
      tagline: "AI-powered social media content creation",
      description: "Buffer's AI Assistant helps you create engaging social media content. It can repurpose content, generate post ideas, and help you maintain a consistent publishing schedule across platforms.",
      category: "Social Media",
      pricing: "Freemium",
      priceDetails: "from $6/mo",
      websiteUrl: "https://buffer.com",
      iconColor: "#3B82F6",
      iconInitials: "BF",
      votes: 29876,
      saves: 10890,
      views: 360000,
      rating: 4.3,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2023-06-01T00:00:00Z",
      features: ["Post generation", "Content repurposing", "Scheduling", "Analytics", "Multi-platform", "Team collaboration"],
      tags: ["social media", "content", "scheduling", "marketing", "automation"]
    },
    {
      id: "54",
      name: "Opus Clip",
      slug: "opus-clip",
      tagline: "AI-powered short video creator from long content",
      description: "Opus Clip uses AI to automatically turn long videos into viral short clips. It identifies the most engaging moments, adds captions, and reformats content for platforms like TikTok and YouTube Shorts.",
      category: "Videos",
      pricing: "Freemium",
      priceDetails: "from $9/mo",
      websiteUrl: "https://opus.pro",
      iconColor: "#8B5CF6",
      iconInitials: "OP",
      votes: 38901,
      saves: 14560,
      views: 490000,
      rating: 4.6,
      isFeatured: true,
      isNew: true,
      isTrending: true,
      releasedAt: "2023-09-01T00:00:00Z",
      features: ["Auto-clipping", "Virality score", "Auto-captions", "B-roll", "Reframing", "Multi-platform export"],
      tags: ["video", "clips", "social media", "content", "automation"]
    },
    {
      id: "55",
      name: "PhotoRoom",
      slug: "photoroom",
      tagline: "AI photo editing for product and portrait images",
      description: "PhotoRoom uses AI to remove backgrounds, create product photos, and edit images instantly. Perfect for e-commerce sellers, marketers, and anyone who needs professional-looking photos quickly.",
      category: "Images",
      pricing: "Freemium",
      priceDetails: "from $10/mo",
      websiteUrl: "https://photoroom.com",
      iconColor: "#6366F1",
      iconInitials: "PR",
      votes: 42345,
      saves: 15670,
      views: 540000,
      rating: 4.5,
      isFeatured: false,
      isNew: false,
      isTrending: false,
      releasedAt: "2019-01-01T00:00:00Z",
      features: ["Background removal", "Product photos", "Batch editing", "Templates", "AI shadows", "API access"],
      tags: ["photo editing", "e-commerce", "background removal", "product photos", "design"]
    }
  ];

  return tools;
};

export class MemStorage implements IStorage {
  private users: Map<string, User>;
  private tools: AITool[];

  constructor() {
    this.users = new Map();
    this.tools = generateMockTools();
  }

  async getUser(id: string): Promise<User | undefined> {
    return this.users.get(id);
  }

  async getUserByUsername(username: string): Promise<User | undefined> {
    return Array.from(this.users.values()).find(
      (user) => user.username === username,
    );
  }

  async createUser(insertUser: InsertUser): Promise<User> {
    const id = randomUUID();
    const user: User = { ...insertUser, id };
    this.users.set(id, user);
    return user;
  }

  async getAllTools(): Promise<AITool[]> {
    return this.tools;
  }

  async getToolBySlug(slug: string): Promise<AITool | undefined> {
    return this.tools.find((tool) => tool.slug === slug);
  }

  async getToolById(id: string): Promise<AITool | undefined> {
    return this.tools.find((tool) => tool.id === id);
  }

  async searchTools(query: SearchQuery): Promise<ToolsResponse> {
    let filtered = [...this.tools];

    if (query.query) {
      const searchTerm = query.query.toLowerCase();
      filtered = filtered.filter(
        (tool) =>
          tool.name.toLowerCase().includes(searchTerm) ||
          tool.tagline.toLowerCase().includes(searchTerm) ||
          tool.description.toLowerCase().includes(searchTerm) ||
          tool.category.toLowerCase().includes(searchTerm) ||
          tool.tags.some((tag) => tag.toLowerCase().includes(searchTerm))
      );
    }

    if (query.category) {
      filtered = filtered.filter(
        (tool) => tool.category.toLowerCase() === query.category?.toLowerCase()
      );
    }

    if (query.pricing) {
      filtered = filtered.filter(
        (tool) => tool.pricing.toLowerCase() === query.pricing?.toLowerCase()
      );
    }

    switch (query.sort) {
      case "popular":
        filtered.sort((a, b) => b.votes - a.votes);
        break;
      case "trending":
        filtered.sort((a, b) => (b.isTrending ? 1 : 0) - (a.isTrending ? 1 : 0) || b.votes - a.votes);
        break;
      case "top-rated":
        filtered.sort((a, b) => b.rating - a.rating);
        break;
      case "new":
      default:
        filtered.sort((a, b) => new Date(b.releasedAt).getTime() - new Date(a.releasedAt).getTime());
        break;
    }

    const page = query.page || 1;
    const limit = query.limit || 30;
    const startIndex = (page - 1) * limit;
    const paginatedTools = filtered.slice(startIndex, startIndex + limit);

    return {
      tools: paginatedTools,
      total: filtered.length,
      page,
      totalPages: Math.ceil(filtered.length / limit),
    };
  }

  async getFeaturedTools(): Promise<FeaturedToolsResponse> {
    const featured = this.tools.filter((tool) => tool.isFeatured).slice(0, 8);
    const trending = this.tools.filter((tool) => tool.isTrending).slice(0, 8);
    const justReleased = [...this.tools]
      .sort((a, b) => new Date(b.releasedAt).getTime() - new Date(a.releasedAt).getTime())
      .slice(0, 8);

    return { featured, trending, justReleased };
  }

  async getRelatedTools(category: string, excludeId?: string): Promise<AITool[]> {
    return this.tools
      .filter((tool) => tool.category === category && tool.id !== excludeId)
      .slice(0, 6);
  }
}

export const storage = new MemStorage();
